import I18n from "@app/languages/I18n";

export type OS = "ios" | "android";

export type TypeNotification =
  | "success"
  | "warning"
  | "info"
  | "error"
  | "points";

export const NOTIFICATION_TYPE = {
  SUCCESS: "success" as TypeNotification,
  WARNING: "warning" as TypeNotification,
  INFO: "info" as TypeNotification,
  ERROR: "error" as TypeNotification,
  POINTS: "points" as TypeNotification,
};

export enum TRANSACTION_TYPE {
  EXPENSE = "EXPENSE",
  INCOME = "INCOME",
}

export enum OPTIONS_PERIOD {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum TRANSACTION_OPTIONS {
  RECURRENCE = "recurrence",
  INSTALLMENT = "installment",
}

export type TCategorySugestion = {
  name: string;
  color: string;
  icon: string;
  type: TRANSACTION_TYPE;
};

export type MONTH_PERIOD = "PREVIOUS" | "CURRENT" | "NEXT";

export const months = [
  I18n.t("months.january"),
  I18n.t("months.february"),
  I18n.t("months.march"),
  I18n.t("months.april"),
  I18n.t("months.may"),
  I18n.t("months.june"),
  I18n.t("months.july"),
  I18n.t("months.august"),
  I18n.t("months.september"),
  I18n.t("months.october"),
  I18n.t("months.november"),
  I18n.t("months.december"),
];

export const profileMenu: {
  icon: string;
  name: string;
  action: (action?: () => void) => void | null;
}[] = [
  {
    icon: "log-out",
    name: "Sair",
    action: (callback?: () => void) => {
      if (callback) return callback();
      return null;
    },
  },
];

export const expensesCategorySugestion: TCategorySugestion[] = [
  {
    name: I18n.t("categories.suggestions.alimentation"),
    color: "#FF0000",
    icon: "food-drumstick",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.transport"),
    color: "#000",
    icon: "bus",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.leisure"),
    color: "#FF8072",
    icon: "gamepad-variant",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.fuel"),
    color: "#E6A22E",
    icon: "fuel",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.clothes"),
    color: "#8CC40B",
    icon: "tshirt-crew",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.services"),
    color: "#302FF5",
    icon: "file-document",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.household_expenses"),
    color: "#6B0531",
    icon: "home-analytics",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.supermarket"),
    color: "#8C20DB",
    icon: "cart",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.education"),
    color: "#18A1F2",
    icon: "book-education",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.health"),
    color: "#00850F",
    icon: "heart",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.travel"),
    color: "#FF6F01",
    icon: "airplane",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.aesthetics"),
    color: "#4DB380",
    icon: "hair-dryer",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.digital_services"),
    color: "#6680B3",
    icon: "television",
    type: TRANSACTION_TYPE.EXPENSE,
  },
  {
    name: I18n.t("categories.suggestions.other"),
    color: "#b0b0b0",
    icon: "dots-horizontal-circle",
    type: TRANSACTION_TYPE.EXPENSE,
  },
];

export const incomesCategorySugestion: TCategorySugestion[] = [
  {
    name: I18n.t("categories.suggestions.salary"),
    color: "#66991A",
    icon: "cash",
    type: TRANSACTION_TYPE.INCOME,
  },
  {
    name: I18n.t("categories.suggestions.bonus"),
    color: "#00B3E6",
    icon: "chart-timeline-variant-shimmer",
    type: TRANSACTION_TYPE.INCOME,
  },
];

export const iconsSugestion = [
  "silverware-variant",
  "line-scan",
  "umbrella-beach",
  "flag",
  "pill",
  "cash",
  "dog",
  "foot-print",
  "music",
  "movie-open",
  "shopping",
  "tree",
  "kettlebell",
  "microsoft-xbox-controller",
  "movie",
  "ninja",
  "glass-mug",
  "incognito-circle",
  "lipstick",
  "ring",
  "medical-bag",
  "piggy-bank",
  "plus-thick",
  "baby-bottle-outline",
  "baby",
  "bathtub",
  "battery",
  "bicycle",
  "book-open-variant",
  "cellphone",
  "chart-line",
  "tooth",
  "train",
  "truck",
  "wallet",
  "web",
];

export const colorsSugestion = [
  "#FFB399",
  "#FF33FF",
  "#8e9F99",
  "#E6B333",
  "#3366E6",
  "#B34D4D",
  "#809900",
  "#E6B3B3",
  "#6680B3",
  "#FF99E6",
  "#CCFF1A",
  "#E6331A",
  "#33FFCC",
  "#B366CC",
  "#4D8000",
  "#B33300",
  "#CC80CC",
  "#66664D",
  "#991AFF",
  "#4DB3FF",
  "#E666B3",
  "#33991A",
  "#B3B31A",
  "#FF3380",
  "#4DB380",
  "#6666FF",
];

export type Currency = { name: string; code: string };

export const currencyList: Currency[] = [
  { name: I18n.t("currencies.afghan_afghani"), code: "AFA" },
  { name: I18n.t("currencies.albanian_lek"), code: "ALL" },
  { name: I18n.t("currencies.algerian_dinar"), code: "DZD" },
  { name: I18n.t("currencies.angolan_kwanza"), code: "AOA" },
  { name: I18n.t("currencies.argentine_peso"), code: "ARS" },
  { name: I18n.t("currencies.armenian_dram"), code: "AMD" },
  { name: I18n.t("currencies.aruban_florin"), code: "AWG" },
  { name: I18n.t("currencies.australian_dollar"), code: "AUD" },
  { name: I18n.t("currencies.azerbaijani_manat"), code: "AZN" },
  { name: I18n.t("currencies.bahamian_dollar"), code: "BSD" },
  { name: I18n.t("currencies.bahraini_dinar"), code: "BHD" },
  { name: I18n.t("currencies.bangladeshi_taka"), code: "BDT" },
  { name: I18n.t("currencies.barbadian_dollar"), code: "BBD" },
  { name: I18n.t("currencies.belarusian_ruble"), code: "BYR" },
  { name: I18n.t("currencies.belgian_franc"), code: "BEF" },
  { name: I18n.t("currencies.belize_dollar"), code: "BZD" },
  { name: I18n.t("currencies.bermudan_dollar"), code: "BMD" },
  { name: I18n.t("currencies.bhutanese_ngultrum"), code: "BTN" },
  { name: I18n.t("currencies.bitcoin"), code: "BTC" },
  { name: I18n.t("currencies.bolivian_boliviano"), code: "BOB" },
  {
    name: I18n.t("currencies.bosnia-herzegovina_convertible_mark"),
    code: "BAM",
  },
  { name: I18n.t("currencies.botswanan_pula"), code: "BWP" },
  { name: I18n.t("currencies.brazilian_real"), code: "BRL" },
  { name: I18n.t("currencies.british_pound_sterling"), code: "GBP" },
  { name: I18n.t("currencies.brunei_dollar"), code: "BND" },
  { name: I18n.t("currencies.bulgarian_lev"), code: "BGN" },
  { name: I18n.t("currencies.burundian_franc"), code: "BIF" },
  { name: I18n.t("currencies.cambodian_riel"), code: "KHR" },
  { name: I18n.t("currencies.canadian_dollar"), code: "CAD" },
  { name: I18n.t("currencies.cape_verdean_escudo"), code: "CVE" },
  { name: I18n.t("currencies.cayman_islands_dollar"), code: "KYD" },
  { name: I18n.t("currencies.cfa_franc_bceao"), code: "XOF" },
  { name: I18n.t("currencies.cfa_franc_beac"), code: "XAF" },
  { name: I18n.t("currencies.cfp_franc"), code: "XPF" },
  { name: I18n.t("currencies.chilean_peso"), code: "CLP" },
  { name: I18n.t("currencies.chinese_yuan"), code: "CNY" },
  { name: I18n.t("currencies.colombian_peso"), code: "COP" },
  { name: I18n.t("currencies.comorian_franc"), code: "KMF" },
  { name: I18n.t("currencies.congolese_franc"), code: "CDF" },
  { name: I18n.t("currencies.costa_rican_colã³n"), code: "CRC" },
  { name: I18n.t("currencies.croatian_kuna"), code: "HRK" },
  { name: I18n.t("currencies.cuban_convertible_peso"), code: "CUC" },
  { name: I18n.t("currencies.czech_republic_koruna"), code: "CZK" },
  { name: I18n.t("currencies.danish_krone"), code: "DKK" },
  { name: I18n.t("currencies.djiboutian_franc"), code: "DJF" },
  { name: I18n.t("currencies.dominican_peso"), code: "DOP" },
  { name: I18n.t("currencies.east_caribbean_dollar"), code: "XCD" },
  { name: I18n.t("currencies.egyptian_pound"), code: "EGP" },
  { name: I18n.t("currencies.eritrean_nakfa"), code: "ERN" },
  { name: I18n.t("currencies.estonian_kroon"), code: "EEK" },
  { name: I18n.t("currencies.ethiopian_birr"), code: "ETB" },
  { name: I18n.t("currencies.euro"), code: "EUR" },
  { name: I18n.t("currencies.falkland_islands_pound"), code: "FKP" },
  { name: I18n.t("currencies.fijian_dollar"), code: "FJD" },
  { name: I18n.t("currencies.gambian_dalasi"), code: "GMD" },
  { name: I18n.t("currencies.georgian_lari"), code: "GEL" },
  { name: I18n.t("currencies.german_mark"), code: "DEM" },
  { name: I18n.t("currencies.ghanaian_cedi"), code: "GHS" },
  { name: I18n.t("currencies.gibraltar_pound"), code: "GIP" },
  { name: I18n.t("currencies.greek_drachma"), code: "GRD" },
  { name: I18n.t("currencies.guatemalan_quetzal"), code: "GTQ" },
  { name: I18n.t("currencies.guinean_franc"), code: "GNF" },
  { name: I18n.t("currencies.guyanaese_dollar"), code: "GYD" },
  { name: I18n.t("currencies.haitian_gourde"), code: "HTG" },
  { name: I18n.t("currencies.honduran_lempira"), code: "HNL" },
  { name: I18n.t("currencies.hong_kong_dollar"), code: "HKD" },
  { name: I18n.t("currencies.hungarian_forint"), code: "HUF" },
  { name: I18n.t("currencies.icelandic_krã³na"), code: "ISK" },
  { name: I18n.t("currencies.indian_rupee"), code: "INR" },
  { name: I18n.t("currencies.indonesian_rupiah"), code: "IDR" },
  { name: I18n.t("currencies.iranian_rial"), code: "IRR" },
  { name: I18n.t("currencies.iraqi_dinar"), code: "IQD" },
  { name: I18n.t("currencies.israeli_new_sheqel"), code: "ILS" },
  { name: I18n.t("currencies.italian_lira"), code: "ITL" },
  { name: I18n.t("currencies.jamaican_dollar"), code: "JMD" },
  { name: I18n.t("currencies.japanese_yen"), code: "JPY" },
  { name: I18n.t("currencies.jordanian_dinar"), code: "JOD" },
  { name: I18n.t("currencies.kazakhstani_tenge"), code: "KZT" },
  { name: I18n.t("currencies.kenyan_shilling"), code: "KES" },
  { name: I18n.t("currencies.kuwaiti_dinar"), code: "KWD" },
  { name: I18n.t("currencies.kyrgystani_som"), code: "KGS" },
  { name: I18n.t("currencies.laotian_kip"), code: "LAK" },
  { name: I18n.t("currencies.latvian_lats"), code: "LVL" },
  { name: I18n.t("currencies.lebanese_pound"), code: "LBP" },
  { name: I18n.t("currencies.lesotho_loti"), code: "LSL" },
  { name: I18n.t("currencies.liberian_dollar"), code: "LRD" },
  { name: I18n.t("currencies.libyan_dinar"), code: "LYD" },
  { name: I18n.t("currencies.lithuanian_litas"), code: "LTL" },
  { name: I18n.t("currencies.macanese_pataca"), code: "MOP" },
  { name: I18n.t("currencies.macedonian_denar"), code: "MKD" },
  { name: I18n.t("currencies.malagasy_ariary"), code: "MGA" },
  { name: I18n.t("currencies.malawian_kwacha"), code: "MWK" },
  { name: I18n.t("currencies.malaysian_ringgit"), code: "MYR" },
  { name: I18n.t("currencies.maldivian_rufiyaa"), code: "MVR" },
  { name: I18n.t("currencies.mauritanian_ouguiya"), code: "MRO" },
  { name: I18n.t("currencies.mauritian_rupee"), code: "MUR" },
  { name: I18n.t("currencies.mexican_peso"), code: "MXN" },
  { name: I18n.t("currencies.moldovan_leu"), code: "MDL" },
  { name: I18n.t("currencies.mongolian_tugrik"), code: "MNT" },
  { name: I18n.t("currencies.moroccan_dirham"), code: "MAD" },
  { name: I18n.t("currencies.mozambican_metical"), code: "MZM" },
  { name: I18n.t("currencies.myanmar_kyat"), code: "MMK" },
  { name: I18n.t("currencies.namibian_dollar"), code: "NAD" },
  { name: I18n.t("currencies.nepalese_rupee"), code: "NPR" },
  { name: I18n.t("currencies.netherlands_antillean_guilder"), code: "ANG" },
  { name: I18n.t("currencies.new_taiwan_dollar"), code: "TWD" },
  { name: I18n.t("currencies.new_zealand_dollar"), code: "NZD" },
  { name: I18n.t("currencies.nicaraguan_cã³rdoba"), code: "NIO" },
  { name: I18n.t("currencies.nigerian_naira"), code: "NGN" },
  { name: I18n.t("currencies.north_korean_won"), code: "KPW" },
  { name: I18n.t("currencies.norwegian_krone"), code: "NOK" },
  { name: I18n.t("currencies.omani_rial"), code: "OMR" },
  { name: I18n.t("currencies.pakistani_rupee"), code: "PKR" },
  { name: I18n.t("currencies.panamanian_balboa"), code: "PAB" },
  { name: I18n.t("currencies.papua_new_guinean_kina"), code: "PGK" },
  { name: I18n.t("currencies.paraguayan_guarani"), code: "PYG" },
  { name: I18n.t("currencies.peruvian_nuevo_sol"), code: "PEN" },
  { name: I18n.t("currencies.philippine_peso"), code: "PHP" },
  { name: I18n.t("currencies.polish_zloty"), code: "PLN" },
  { name: I18n.t("currencies.qatari_rial"), code: "QAR" },
  { name: I18n.t("currencies.romanian_leu"), code: "RON" },
  { name: I18n.t("currencies.russian_ruble"), code: "RUB" },
  { name: I18n.t("currencies.rwandan_franc"), code: "RWF" },
  { name: I18n.t("currencies.salvadoran_colã³n"), code: "SVC" },
  { name: I18n.t("currencies.samoan_tala"), code: "WST" },
  { name: I18n.t("currencies.saudi_riyal"), code: "SAR" },
  { name: I18n.t("currencies.serbian_dinar"), code: "RSD" },
  { name: I18n.t("currencies.seychellois_rupee"), code: "SCR" },
  { name: I18n.t("currencies.sierra_leonean_leone"), code: "SLL" },
  { name: I18n.t("currencies.singapore_dollar"), code: "SGD" },
  { name: I18n.t("currencies.slovak_koruna"), code: "SKK" },
  { name: I18n.t("currencies.solomon_islands_dollar"), code: "SBD" },
  { name: I18n.t("currencies.somali_shilling"), code: "SOS" },
  { name: I18n.t("currencies.south_african_rand"), code: "ZAR" },
  { name: I18n.t("currencies.south_korean_won"), code: "KRW" },
  { name: I18n.t("currencies.special_drawing_rights"), code: "XDR" },
  { name: I18n.t("currencies.sri_lankan_rupee"), code: "LKR" },
  { name: I18n.t("currencies.st._helena_pound"), code: "SHP" },
  { name: I18n.t("currencies.sudanese_pound"), code: "SDG" },
  { name: I18n.t("currencies.surinamese_dollar"), code: "SRD" },
  { name: I18n.t("currencies.swazi_lilangeni"), code: "SZL" },
  { name: I18n.t("currencies.swedish_krona"), code: "SEK" },
  { name: I18n.t("currencies.swiss_franc"), code: "CHF" },
  { name: I18n.t("currencies.syrian_pound"), code: "SYP" },
  { name: I18n.t("currencies.são_tomé_and_príncipe_dobra"), code: "STD" },
  { name: I18n.t("currencies.tajikistani_somoni"), code: "TJS" },
  { name: I18n.t("currencies.tanzanian_shilling"), code: "TZS" },
  { name: I18n.t("currencies.thai_baht"), code: "THB" },
  { name: I18n.t("currencies.tongan_pa'anga"), code: "TOP" },
  { name: I18n.t("currencies.trinidad_&_tobago_dollar"), code: "TTD" },
  { name: I18n.t("currencies.tunisian_dinar"), code: "TND" },
  { name: I18n.t("currencies.turkish_lira"), code: "TRY" },
  { name: I18n.t("currencies.turkmenistani_manat"), code: "TMT" },
  { name: I18n.t("currencies.ugandan_shilling"), code: "UGX" },
  { name: I18n.t("currencies.ukrainian_hryvnia"), code: "UAH" },
  { name: I18n.t("currencies.united_arab_emirates_dirham"), code: "AED" },
  { name: I18n.t("currencies.uruguayan_peso"), code: "UYU" },
  { name: I18n.t("currencies.us_dollar"), code: "USD" },
  { name: I18n.t("currencies.uzbekistan_som"), code: "UZS" },
  { name: I18n.t("currencies.vanuatu_vatu"), code: "VUV" },
  { name: I18n.t("currencies.venezuelan_bolãvar"), code: "VEF" },
  { name: I18n.t("currencies.vietnamese_dong"), code: "VND" },
  { name: I18n.t("currencies.yemeni_rial"), code: "YER" },
  { name: I18n.t("currencies.zambian_kwacha"), code: "ZMK" },
];
